name: "Push Build to Artifactory"
on: push
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout Code
       uses: actions/checkout@v4

     - name: Deploy
       run: 
          curl -H "Authorization: Bearer ${{ secrets.JF_TOKEN }}" \
               -X PUT \
               -T file.txt \
               "${{ secrets.JF_URL }}"
